name: JIRENGU_CI

on: pull_request_target
jobs:
  homework-judgement:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ðŸŽ‰ æ„Ÿè°¢æ‚¨æäº¤Pull Requestï¼è¯·ç¨ç­‰ç‰‡åˆ»ï¼Œæˆ‘ä»¬å·²ç»å°†å…¶æäº¤åˆ°CIè¿›è¡Œæ£€æŸ¥ï¼Œä¸€æ—¦æœ‰ç»“æžœä¼šç«‹å³é€šçŸ¥æ‚¨ï¼
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Comment PR if tests pass
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ' ðŸŽ‰ Congratulation!ðŸŽ‰ðŸŽ‰ðŸŽ‰ æ‰€æœ‰æµ‹è¯•å‡å·²é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šè‡ªåŠ¨åˆå¹¶ä½ çš„PRï¼Œä¹‹åŽä¼šrevertæ–¹ä¾¿å…¶ä»–å°ä¼™ä¼´ç»§ç»­ç»ƒä¹ ã€‚å¯ä»¥åŽ»è¯•è¯•åˆ«çš„æŒ‘æˆ˜ï¼'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR if tests fail
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'ä½ çš„ä»£ç å¥½åƒæ²¡æœ‰é€šè¿‡æµ‹è¯•. ðŸ˜ž è¯·ä»”ç»†æ£€æŸ¥ä½ çš„ä»£ç ï¼Œè¯¦æƒ…å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°ï¼š [ci logs](${{ github.event.pull_request._links.html.href }}/checks) '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR if tests pass
        if: ${{ success() }}
        run: |
          # Merge PR
          response=$(curl -X PUT \
            -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge)
          # Get the SHA of the merge commit
          sha=$(echo "$response" | jq -r '.sha')
          echo "merge_commit_sha=$sha" >> $GITHUB_ENV
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Revert pushed commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase
          git revert -m 1 ${{ env.merge_commit_sha }}
          git push
